name: Spacewar_test

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore Spacewar.sln

      - name: Build
        run: dotnet build Spacewar.sln --no-restore /p:ContinuousIntegrationBuild=true

      - name: Unittest and coverage
        run: dotnet test Spacewar.sln /p:CollectCoverage=true /p:Threshold=100 /p:ThresholdType=line

      - name: Check style
        run: dotnet format --verify-no-changes